// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace Vcc.SocialNet.UserService.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vcc.SocialNet.UserService.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(15);

                    b.Property<string>("City")
                        .HasMaxLength(15);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(15);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<short>("Position");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);

                    b.Property<string>("Province")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "160 Borrows Street",
                            CellPhone = "4168493938",
                            City = "Toronto",
                            DateOfBirth = new DateTime(1972, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joon.choi@gmail.com",
                            FirstName = "Joon",
                            Gender = "Male",
                            HomePhone = "4169026859",
                            LastName = "Choi",
                            Position = (short)8,
                            PostalCode = "L3J 2S9",
                            Province = "ON"
                        },
                        new
                        {
                            Id = 2,
                            Address = "160 Borrows Street",
                            CellPhone = "4168493938",
                            City = "Toronto",
                            DateOfBirth = new DateTime(1972, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joon.choi@gmail.com",
                            FirstName = "Joon2",
                            Gender = "Male",
                            HomePhone = "4169026859",
                            LastName = "Choi",
                            Position = (short)8,
                            PostalCode = "L3J 2S9",
                            Province = "ON"
                        },
                        new
                        {
                            Id = 3,
                            Address = "160 Borrows Street",
                            CellPhone = "4168493938",
                            City = "Toronto",
                            DateOfBirth = new DateTime(1972, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joon.choi@gmail.com",
                            FirstName = "Joon3",
                            Gender = "Male",
                            HomePhone = "4169026859",
                            LastName = "Choi",
                            Position = (short)8,
                            PostalCode = "L3J 2S9",
                            Province = "ON"
                        },
                        new
                        {
                            Id = 4,
                            Address = "160 Borrows Street",
                            CellPhone = "4168493938",
                            City = "Toronto",
                            DateOfBirth = new DateTime(1972, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joon.choi@gmail.com",
                            FirstName = "Joon4",
                            Gender = "Male",
                            HomePhone = "4169026859",
                            LastName = "Choi",
                            Position = (short)8,
                            PostalCode = "L3J 2S9",
                            Province = "ON"
                        },
                        new
                        {
                            Id = 5,
                            Address = "160 Borrows Street",
                            CellPhone = "4168493938",
                            City = "Toronto",
                            DateOfBirth = new DateTime(1972, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joon.choi@gmail.com",
                            FirstName = "Joon5",
                            Gender = "Male",
                            HomePhone = "4169026859",
                            LastName = "Choi",
                            Position = (short)8,
                            PostalCode = "L3J 2S9",
                            Province = "ON"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
